### ISSUE TITLE
TypeError: cb.apply is not a function

### ISSUE THREAD

**Issue by buxoman** [isaacs/node-graceful-fs#192]
% uname -a
Darwin xpace7 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

% npm install graceful-fs -g 
+ graceful-fs@4.2.4
added 1 package in 0.252s

% gitbook -V
CLI version: 2.3.2
Installing GitBook 3.2.3
/usr/local/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:287
      if (cb) cb.apply(this, arguments)
                 ^

TypeError: cb.apply is not a function
    at /usr/local/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:177:5)

**Comment by yberstad** [comment]
Hi!

I'm having the same issue, @buxoman did you find a solution?

**Comment by buxoman** [comment]
@yberstad I have no experience on javascript and just want to write markdown using gitbook.

**Comment by coreyfarrell** [comment]
Your install of `gitboot` is not using graceful-fs@4.2.4 since you got this error from polyfills.js:287.  From what I can tell it must be using 4.1.11 or older in one or more places.  This might be fixed by reinstalling `gitbook-cli`, if not this is a bug where gitbook or one of its dependencies is pulling in a broken version of graceful-fs.  This issue was fixed in graceful-fs@4.2.0.

**Comment by yberstad** [comment]
I fixed the issue by adding this to package.json (after devDependencies: {})
```
  "resolutions": {
    "**/graceful-fs": "^4.2.4"
  }
```

**Comment by coreyfarrell** [comment]
It looks like the `gitbook` CLI is abandoned by its developers in favor of a paid service, see https://github.com/GitbookIO/gitbook#%EF%B8%8F-deprecation-warning.

Since the graceful-fs bug was fixed nearly 4 years ago and does not require a semver-major bump nothing further can be done by us.  I don't know if alternatives to `gitbook` exist, this might be worth researching if the current situation is untenable for you.

**Comment by willin** [comment]
> I fixed the issue by adding this to package.json (after devDependencies: {})
> 
> ```
>   "resolutions": {
>     "**/graceful-fs": "^4.2.4"
>   }
> ```

not working https://travis-ci.org/github/willin/codewars.js.cool/jobs/715362713#L204

**Comment by willin** [comment]
https://github.com/willin/codewars.js.cool/blob/master/package.json

**Comment by greyltc** [comment]
Yeah. That also doesn't work for me.

**Comment by greyltc** [comment]
If anyone has a working solution for this for the abandoned gitbook-cli, please let us know at https://github.com/GitbookIO/gitbook-cli/issues/110
I'll try to make a fork of gitbook-cli it so that the community has something that continues to work, but today I'm unable to fix this.

**Comment by MwumLi** [comment]
The main reason is that [fs.stat support bigint ](http://nodejs.cn/api/fs/fs_stat_path_options_callback.html) since node v10.5.0:  
![image](https://user-images.githubusercontent.com/6889433/107945118-1fa64780-6fca-11eb-902e-3e00ab23c9bc.png)

But before v10.5.0, [fs.js - Loop ](https://github.com/nodejs/node/blob/v10.16.0/lib/fs.js#L1567-L1597):  
![image](https://user-images.githubusercontent.com/6889433/107949216-e4a71280-6fcf-11eb-8d2d-a90992c1eaef.png)

After v10.5.0, [fs.js - Loop ](https://github.com/nodejs/node/blob/v12.18.3/lib/fs.js#L1724-L1753):   
![image](https://user-images.githubusercontent.com/6889433/107949648-93e3e980-6fd0-11eb-940a-995c89397b7e.png)

The simplest method is limit node version, If your can change node version:    
```
  "engines": {
    "node": ">=8.11.1 < 11.15.0"
  }
```

The once and for all method is to send a patch package for graceful-fs "stat" to support option for second param

**Comment by synergiator** [comment]
the "engines" patch does not work with the RN community android build, the error remains.
