### ISSUE TITLE
fs.lstatSync() isn't instance of fs.Stats on Node.js 0.12

### ISSUE THREAD

**Issue by okuryu** [isaacs/node-graceful-fs#35]
Result of `fs.lstatSync()` isn't instance of `fs.Stats` with `graceful-fs@3.0.4` on Node.js 0.11. This problem doesn't occur with `graceful-fs@3.0.3`.

Example code (`index.js`) as follows.

```js
var gfs = require("graceful-fs");
var fs = require("fs");
var path = "file1.txt";

gfs.writeFileSync(path, "Files Test");
console.log(gfs.lstatSync(path) instanceof fs.Stats);
gfs.unlinkSync("file1.txt");
```

`graceful-fs@3.0.3`:

```
$ node -v
v0.11.14
$ node index.js
true
```

`graceful-fs@3.0.4`:

```
$ node -v
v0.11.14
$ node index.js
false
```

**Comment by cainjonm** [comment]
This also seems to effect the `fs` module globally too. Which i think is caused by https://github.com/joyent/node/commit/e9ce8fc82a6d12e790511b62852e820d8be03186

When graceful-fs is require'd, the Stats constructor is rebound in native code (https://github.com/joyent/node/blob/e9ce8fc82a6d12e790511b62852e820d8be03186/lib/fs.js#L151). If this makes sense, it would explain why importing graceful-fs seems to effect fs too (i think?). I have included code to show what I mean.

Using `node v0.12.2` and graceful-fs version `3.0.6`.
```
var fs = require("fs"); 
var path = "file1.txt"; 
 
fs.writeFileSync(path, "Files Test");
fs.stat(path, function (err, stat) { 
    console.log("A", stat instanceof fs.Stats); // true 
 
    var gfs = require("graceful-fs"); 
 
    fs.stat(path, function (err, stat) { 
        console.log("B", stat instanceof fs.Stats); // false <-- :(
        console.log("C", stat instanceof gfs.Stats); // true 
    }); 
}); 
```

**Comment by etiktin** [comment]
@cainjonm, you are correct. The main issue here is breaking the global fs module by changing the Stats constructor that the native code uses.

PR #42 fixes it.

For the time being if you want to fix it in your code, you can add the following lines after the first load of gfs:
```javascript
var binding = process.binding('fs')
if (binding.FSInitialize) {
  binding.FSInitialize(fs.Stats)
  gfs.Stats = fs.Stats
}
```

**Comment by okuryu** [comment]
This seems to be resolved in graceful-fs v4.x, right?

**Comment by etiktin** [comment]
Yes, it's resolved. 
To be sure everything else works for you, I suggest you run `npm test` on your platform and see that everything works for you (on Windows, it seems that some of the tests fail, but it might be an issue with rimraf).
