### ISSUE TITLE
question about implementation details

### ISSUE THREAD

**Issue by thisconnect** [isaacs/node-graceful-fs#48]
Hi, I like graceful-fs an am thinking to use it in http://npmjs.com/package/fildes I have a couple of questions and hope it is ok to ask here.

1)
Retrying the queue, happens on some of the 'shimed' methods like close, closeSync. Does that work in multiple child processes that each try to write many files, as I suppose if one child process gets too many file descriptors error and the other process then calls close, the first isn't informed that something happend?

2)
What does the polyfills.js and legacy-streams.js do? and what impact has it if I only want to use Node.js 4.x

3)
what is require('constants'), seems to be something Node.js internal is that correct? Is there any documentation on it somewhere?

Thanks and I hope you don't mind me asking here.

**Comment by thisconnect** [comment]
To partly answer my own question

>  flags can also be a number as documented by open(2); commonly used constants are available from require('constants'). On Windows, flags are translated to their equivalent ones where applicable, e.g. O_WRONLY to FILE_GENERIC_WRITE, or O_EXCL|O_CREAT to CREATE_NEW, as accepted by CreateFileW.

  https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback

**Comment by isaacs** [comment]
1. File descriptors are per-process.  So, you typically don't open a file descriptor in one process and close it in another.  This _can_ be done by sending the file descriptors via a sendmsg syscall, but that's rare.  Even if you do sendmsg file descriptors between processes, the actual limits that cause EMFILE and ENFILE errors are per-process, so they'll requeue the opens in that process when the error is encountered.

2. polyfills.js is polyfills for things that are broken in some versions of node or which don't exist on some operating systems.  For example, lchmod is turned into a no-op instead of a nonexistent function.  legacy-streams.js is there to fix streams in node v0.8.

3. I don't know if there are any documentation pages for require('constants') but it's been there for a very long time.

**Comment by addaleax** [comment]
> I don't know if there are any documentation pages for require('constants') but it's been there for a very long time.

Hope it’s okay to comment here! There is no documentation on it, and while it’s likely going to keep being around for a long time, the long-term direction in which Node is headed is replacing it by explicit `constants` properties of modules, e.g. `fs.constants`, which are available and documented now (in Node >= v6.3.0). See https://github.com/nodejs/node/pull/6534 for a bit of context on that, if you’re interested.

**Comment by isaacs** [comment]
@addaleax Cool.  Since it's only used for older versions (0.6 and before, I believe?) probably we can just add a guard around the require().

**Comment by addaleax** [comment]
I *think* `var constants = fs.constants || require('constants')` would be safe to use here, if that’s what you’re suggesting?

**Comment by isaacs** [comment]
Or even just `try { var constants = require('constants') } catch (e) { constants = {} }` would probably work.  I _believe_ it only uses it when the version is below 0.6.5 or something hella old like that.

**Comment by addaleax** [comment]
Hm – `patchLutimes` seems to use it for the `lutimes` polyfill, and I can’t seem to find `fs.lutimes` on any standard Node.js `fs` module?

I doubt it matters much. :D

**Comment by thisconnect** [comment]
thank you both
