### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by lepatlamass** [isaacs/node-graceful-fs#50]
Hello when ever i tried to install the other dependecies needed for production i got the following errors
npm WARN install Couldn't install optional dependency: Unsupported
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lepat\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! file C:\Users\lepat\AppData\Roaming\npm-cache\graceful-fs\4.1.2\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\lepat\AppData\Roaming\npm-cache\graceful-fs\4.1.2\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp\www\p1\npm-debug.log

thanks for the help

**Comment by isaacs** [comment]
Well, creating a json file with a single null byte is definitely not a graceful-fs bug.  That seems like an issue with either npm, node, or your network.

Perhaps run `npm cache clean` and try again?  Closing because it's not work to be done here, but feel free to keep sharing in this thread to try to debug the issue.
