### ISSUE TITLE
npm WARN deprecated version!

### ISSUE THREAD

**Issue by lovebdsobuj** [isaacs/node-graceful-fs#62]
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

----------

But after command prompt  `npm install -g graceful-fs@^4.0.0`
> npm ERR! No compatible version found: graceful-fs@4.0.0 npm ERR! Valid
> install targets: npm ERR! 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7,
> 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0

----------
Updated with latest `4.1.3` version, but the warn message still...

**Comment by isaacs** [comment]
It looks like your shell is doing something weird with the `^` character.  Also, you need to install it in your application, not globally.

Try this:

```
npm install "graceful-fs@^4.0.0" --save
```

If you still get warnings, then it's because something else is using a deprecated version of graceful-fs.  You can run `npm ls graceful-fs` to see where it lives in your project.  If it's being included by some other module, then you'll need to get them to update their dependency as well.
