### ISSUE TITLE
error with: sudo npm install graceful-fs

### ISSUE THREAD

**Issue by ed-torvalds** [isaacs/node-graceful-fs#77]
```
@archlinux ➜  ~  ᐅ  sudo npm install graceful-fs


npm ERR! Linux 4.7.0-1-zen
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "graceful-fs"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! file /home/edward/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/edward/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/edward/npm-debug.log

```

npm-debug.log [here](https://paste.gnome.org/pbleifzcy)

Please help me out with this issue, I need graceful-fs installed for atom editor

**Comment by isaacs** [comment]
It looks like you have a `package.json` file in your home director that is not actually JSON data.

I don't think that you need to install this explicitly in order to use the atom editor.  I think that Atom installs graceful-fs in its own location.  Maybe you mean that you want to do development on the Atom editor itself?  If so, you should be typing `npm install` in the root of the Atom editor codebase.

Are you working through some kind of how-to or tutorial?  I'm confused about your intent here.
